import { Router } from "express";
import * as controller from "../controllers/groups.js";
import { auth } from "../middleware/auth.js";
import { asyncRoute } from "../utils/asyncRoute.js";
export const groupRoutes = Router();
groupRoutes.use(auth);
groupRoutes.get("/", asyncRoute(controller.list));
groupRoutes.post("/", asyncRoute(controller.create));
groupRoutes.get("/:id", asyncRoute(controller.get));
groupRoutes.post("/:id/members", asyncRoute(controller.addMember));
